// Generated by gencpp from file temp/temp_odom.msg
// DO NOT EDIT!


#ifndef TEMP_MESSAGE_TEMP_ODOM_H
#define TEMP_MESSAGE_TEMP_ODOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace temp
{
template <class ContainerAllocator>
struct temp_odom_
{
  typedef temp_odom_<ContainerAllocator> Type;

  temp_odom_()
    : temp(0.0)
    , x(0.0)
    , y(0.0)  {
    }
  temp_odom_(const ContainerAllocator& _alloc)
    : temp(0.0)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _temp_type;
  _temp_type temp;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::temp::temp_odom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::temp::temp_odom_<ContainerAllocator> const> ConstPtr;

}; // struct temp_odom_

typedef ::temp::temp_odom_<std::allocator<void> > temp_odom;

typedef boost::shared_ptr< ::temp::temp_odom > temp_odomPtr;
typedef boost::shared_ptr< ::temp::temp_odom const> temp_odomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::temp::temp_odom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::temp::temp_odom_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace temp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'temp': ['/home/administrator/catkin_ws/src/temp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::temp::temp_odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::temp::temp_odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::temp::temp_odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::temp::temp_odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::temp::temp_odom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::temp::temp_odom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::temp::temp_odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd83befe417dc082a719340bc80467ca";
  }

  static const char* value(const ::temp::temp_odom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd83befe417dc082ULL;
  static const uint64_t static_value2 = 0xa719340bc80467caULL;
};

template<class ContainerAllocator>
struct DataType< ::temp::temp_odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "temp/temp_odom";
  }

  static const char* value(const ::temp::temp_odom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::temp::temp_odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 temp\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::temp::temp_odom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::temp::temp_odom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temp);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct temp_odom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::temp::temp_odom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::temp::temp_odom_<ContainerAllocator>& v)
  {
    s << indent << "temp: ";
    Printer<double>::stream(s, indent + "  ", v.temp);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEMP_MESSAGE_TEMP_ODOM_H
